import Link from "next/link";
import Breadcrumb from "@/components/navigation/Breadcrumb";
import JsonLd from "@/seo/JsonLd";
import { siteConfig } from "@/config/site";
import type { Build, Unit } from "@/types/content";
import styles from "@/style/page/archive/archive.module.css";

type BuildDetail = { quickAnswer: string; loadout: string[][]; sections: { title: string; paragraphs: string[]; bullets?: string[] }[] };
export default function BuildDetailPage({ build, unit, detail }: { build: Build; unit: Unit; detail: BuildDetail }) { return <main><JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: build.title, description: build.summary, dateModified: siteConfig.lastVerified, author: { "@type": "Organization", name: siteConfig.name }, mainEntityOfPage: `${siteConfig.url}/builds/${build.slug}` }} /><section className={styles.hero}><div className={`container ${styles.heroContent}`}><Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Builds", href: "/builds" }, { label: build.title }]} /><p className={styles.eyebrow}>{build.faction} · {build.difficulty} · {build.version}</p><h1>{build.title}</h1><p>{build.summary}</p></div></section><section className={`container section ${styles.contentGrid}`}><article className={`${styles.mainColumn} ${styles.prose}`}><div className={styles.quickAnswer}><b>Build summary</b><p>{detail.quickAnswer}</p></div><h2>Recommended starting loadout</h2><div className={styles.entryList}>{detail.loadout.map(([label, value, href]) => <Link className={styles.entryRow} href={href} key={label}><span>{label}</span><div><h3>{value}</h3><p>Open the verified record behind this recommendation.</p></div><b>Verify →</b></Link>)}</div>{detail.sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul>}</section>)}<h2>Editorial disclosure</h2><p>This build is reasoned from publicly verified {build.version} unit and item data. It is not official, does not claim exhaustive testing, and should be rechecked when the game version changes.</p></article><aside className={styles.sidebar}><h2>Build profile</h2><p className={styles.sourceBox}><strong>{build.version}</strong><br />Editorial · verified source layer dated {siteConfig.lastVerified}</p><h3>Core record</h3><Link href={`/wiki/units/${unit.slug}`}>{unit.name}</Link><Link href={`/wiki/factions/${unit.factionSlug}`}>{unit.faction}</Link><h3>Related</h3><Link href="/guides/formation-guide">Formation guide</Link><Link href="/wiki/items">Items</Link><Link href="/updates">Updates</Link></aside></section></main>; }
