import Image from "next/image";
import Link from "next/link";
import Breadcrumb from "@/components/navigation/Breadcrumb";
import UnitExplorer from "@/page/wiki/components/UnitExplorer";
import { factions, units } from "@/lib/data/game-content";
import { createMetadata } from "@/seo/metadata";
import styles from "@/style/page/archive/archive.module.css";

export const metadata = createMetadata("Goodly Trials Units", "Browse verified Goodly Trials units by faction, tactic, and STR, AGI, or INT values for v0.300.", "/wiki/units");

export default function UnitsPage() {
  return <main><section className={styles.hero}><Image className={styles.heroImage} src="/images/game/screenshot-1.webp" alt="Goodly Trials board, shop, and selected unit card" fill preload sizes="100vw" /><div className={styles.heroShade} /><div className={`container ${styles.heroContent}`}><Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Wiki", href: "/wiki" }, { label: "Units" }]} /><p className={styles.eyebrow}>Verified unit cards · v0.300</p><h1>Goodly Trials Units</h1><p>Filter the official public unit sample by faction and tactic. Core values remain server-rendered and every detail page links back to its source.</p></div></section><section className="container section"><div className={styles.contentGrid}><div className={styles.mainColumn}><UnitExplorer units={units} /><div className={styles.sectionBlock}><h2>Understanding Goodly Trials Units</h2><p>A unit card combines vitals, attributes, combat values, equipment capacity, one rolled trait, skills, and a tactic. The right reading order is not simply “highest ATK wins”: formation, range, adjacency, gear requirements, and the opposing line change what a recruit can do.</p><h3>Units and factions</h3><p>Public materials describe three factions. {factions.map((faction, index) => <span key={faction.slug}>{index ? ", " : ""}<Link href={`/wiki/factions/${faction.slug}`}>{faction.name}</Link></span>)} each use a different roster logic.</p><h3>Why only six full cards?</h3><p>The official mechanics page currently exposes complete, human-readable values for this verified sample. The archive lists no invented stats for the wider roster and will expand detail records only as source data becomes auditable.</p></div></div><aside className={styles.sidebar}><h2>Unit index</h2><h3>Popular units</h3>{units.slice(0, 5).map((unit) => <Link key={unit.slug} href={`/wiki/units/${unit.slug}`}>{unit.name}</Link>)}<h3>Faction overview</h3>{factions.map((faction) => <Link key={faction.slug} href={`/wiki/factions/${faction.slug}`}>{faction.name}</Link>)}<h3>Related guides</h3><Link href="/guides/formation-guide">Formation guide</Link><Link href="/guides/stats-explained">Stats explained</Link></aside></div></section></main>;
}
